version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  serverless-framework: circleci/serverless-framework@2.0

executors:
  node:
    docker:
      - image: cimg/node:20.0.0
    resource_class: small

commands:
  dependencies:
    steps:
      - run:
          name: Installing node dependencies
          command: sudo pnpm install

  aws:
    steps:
      - aws-cli/setup:
          aws-access-key-id: ACCESS_KEY
          aws-secret-access-key: SECRET_ACCESS_KEY
          aws-region: REGION_NAME

  tests:
    steps:
      - run:
          name: Running Unit Tests
          command: pnpm test

  deploy:
    parameters:
      stage:
        type: string
    steps:
      - serverless-framework/setup
      - run:
          name: Deploying application
          command: serverless deploy --stage << parameters.stage >>

jobs:
  tests:
    executor: node
    steps:
      - checkout
      - dependencies
      - tests

  deploy:
    executor: node
    parameters:
      stage:
        type: string
        default: dev
    steps:
      - checkout
      - dependencies
      - aws
      - deploy:
          stage: << parameters.stage >>

workflows:
  default:
    jobs:
      - tests:
          name: Unit Tests Assurance
          filters:
            branches:
              ignore: /dependabot.*/

      - deploy:
          name: Deployment in Production
          context: aws-shared-key
          stage: prd
          requires: [ "Unit Tests Assurance" ]
          filters:
            branches:
              only: [ "main" ]
